# Generated by Django 3.1.1 on 2020-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='话题')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='关注度')),
            ],
        ),
    ]
